name: scouting
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.3+4

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flutter_candlesticks_chart: ^0.1.1
  intl: ^0.16.1
  characters: ^1.0.0
  http: ^0.12.2
  pedantic: ^1.9.2
  syncfusion_flutter_core: ^18.3.44
  syncfusion_flutter_charts: ^18.2.48
  curved_navigation_bar: ^0.3.4 #latest version
  firebase_core: ^0.5.3
  cloud_firestore: ^0.14.4
  flutter_slidable: ^0.5.7
  


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
   - assets/images/
   - assets/icon/
   - assets/stockjson/
   - assets/icon/scoutingstock.png
  # - assets/images/BOV_ABCB4.png
  # - assets/images/BOV_ABCP11.png
  # - assets/images/BOV_ABEV3.png
  # - assets/images/BOV_ALPA3.png
  # - assets/images/BOV_ALPA4.png
  # - assets/images/BOV_ALUP11.png
  # - assets/images/BOV_AMAR3.png
  # - assets/images/BOV_AMZO34.png
  # - assets/images/BOV_AZUL4.png
  # - assets/images/BOV_B3SA3.png
  # - assets/images/BOV_BAZA3.png
  # - assets/images/BOV_BBAS3.png
  # - assets/images/BOV_BBDC3.png
  # - assets/images/BOV_BBDC4.png
  # - assets/images/BOV_BBFI11B.png
  # - assets/images/BOV_BBSE3.png
  # - assets/images/BOV_BBVJ11.png
  # - assets/images/BOV_BEEF3.png
  # - assets/images/BOV_BEES3.png
  # - assets/images/BOV_BGIP4.png
  # - assets/images/BOV_BIDI4.png
  # - assets/images/BOV_BKBR3.png
  # - assets/images/BOV_BMEB3.png
  # - assets/images/BOV_BMEB4.png
  # - assets/images/BOV_BMLC11B.png
  # - assets/images/BOV_BOBR4.png
  # - assets/images/BOV_BOVA11.png
  # - assets/images/BOV_BRAP3.png
  # - assets/images/BOV_BRAP4.png
  # - assets/images/BOV_BRAX11.png
  # - assets/images/BOV_BRCR11.png
  # - assets/images/BOV_BRDT3.png
  # - assets/images/BOV_BRFS3.png
  # - assets/images/BOV_BRKM5.png
  # - assets/images/BOV_BRML3.png
  # - assets/images/BOV_BRPR3.png
  # - assets/images/BOV_BRSR6.png
  # - assets/images/BOV_BTCRL.png
  # - assets/images/BOV_BTOW3.png
  # - assets/images/BOV_BVMF3.png
  # - assets/images/BOV_CAML3.png
  # - assets/images/BOV_CARD3.png
  # - assets/images/BOV_CCMFUT.png
  # - assets/images/BOV_CCRO3.png
  # - assets/images/BOV_CESP3.png
  # - assets/images/BOV_CESP6.png
  # - assets/images/BOV_CGAS5.png
  # - assets/images/BOV_CIEL3.png
  # - assets/images/BOV_CLSC4.png
  # - assets/images/BOV_CMIG3.png
  # - assets/images/BOV_CMIG4.png
  # - assets/images/BOV_CNTO3.png
  # - assets/images/BOV_COCA34.png
  # - assets/images/BOV_COCE5.png
  # - assets/images/BOV_COGN3.png
  # - assets/images/BOV_CPFE3.png
  # - assets/images/BOV_CPLE3.png
  # - assets/images/BOV_CPLE6.png
  # - assets/images/BOV_CRFB3.png
  # - assets/images/BOV_CSAN3.png
  # - assets/images/BOV_CSMG3.png
  # - assets/images/BOV_CSNA3.png
  # - assets/images/BOV_CTNM4.png
  # - assets/images/BOV_CYRE3.png
  # - assets/images/BOV_DASA3.png
  # - assets/images/BOV_DAX30.png
  # - assets/images/BOV_DIRR3.png
  # - assets/images/BOV_DISB34.png
  # - assets/images/BOV_DIVO11.png
  # - assets/images/BOV_DJIA.png
  # - assets/images/BOV_DOLAR.png
  # - assets/images/BOV_DOLCOM.png
  # - assets/images/BOV_DOLFUT.png
  # - assets/images/BOV_DOLTUR.png
  # - assets/images/BOV_DTEX3.png
  # - assets/images/BOV_ECOO11.png
  # - assets/images/BOV_ECOR3.png
  # - assets/images/BOV_EGIE3.png
  # - assets/images/BOV_ELET3.png
  # - assets/images/BOV_ELET6.png
  # - assets/images/BOV_EMAE4.png
  # - assets/images/BOV_EMBR3.png
  # - assets/images/BOV_ENBR3.png
  # - assets/images/BOV_ENEV3.png
  # - assets/images/BOV_EQTL3.png
  # - assets/images/BOV_ETER3.png
  # - assets/images/BOV_ETHDL.png
  # - assets/images/BOV_EUCA4.png
  # - assets/images/BOV_EURO.png
  # - assets/images/BOV_EUS10Y.png
  # - assets/images/BOV_EVEN3.png
  # - assets/images/BOV_EXXO34.png
  # - assets/images/BOV_EZTC3.png
  # - assets/images/BOV_FAMB11B.png
  # - assets/images/BOV_FERRO62.png
  # - assets/images/BOV_FESA4.png
  # - assets/images/BOV_FHER3.png
  # - assets/images/BOV_FIND11.png
  # - assets/images/BOV_FLMA11.png
  # - assets/images/BOV_FLRY3.png
  # - assets/images/BOV_FRIO3.png
  # - assets/images/BOV_FTSE100.png
  # - assets/images/BOV_GFSA3.png
  # - assets/images/BOV_GGBR3.png
  # - assets/images/BOV_GGBR4.png
  # - assets/images/BOV_GOAU3.png
  # - assets/images/BOV_GOAU4.png
  # - assets/images/BOV_GOLL4.png
  # - assets/images/BOV_GOVE11.png
  # - assets/images/BOV_GRND3.png
  # - assets/images/BOV_GUAR3.png
  # - assets/images/BOV_HAGA4.png
  # - assets/images/BOV_HBOR3.png
  # - assets/images/BOV_HGBS11.png
  # - assets/images/BOV_HGLG11.png
  # - assets/images/BOV_HGRE11.png
  # - assets/images/BOV_HGTX3.png
  # - assets/images/BOV_HSENG.png
  # - assets/images/BOV_HYPE3.png
  # - assets/images/BOV_IBVSP.png
  # - assets/images/BOV_IBXL.png
  # - assets/images/BOV_IBXX.png
  # - assets/images/BOV_ICON.png
  # - assets/images/BOV_IDNT3.png
  # - assets/images/BOV_IEE.png
  # - assets/images/BOV_IFIX.png
  # - assets/images/BOV_IFNC.png
  # - assets/images/BOV_IGTA3.png
  # - assets/images/BOV_IMOB.png
  # - assets/images/BOV_INDFUT.png
  # - assets/images/BOV_INEP4.png
  # - assets/images/BOV_IRBR3.png
  # - assets/images/BOV_ITAG.png
  # - assets/images/BOV_ITSA3.png
  # - assets/images/BOV_ITSA4.png
  # - assets/images/BOV_ITUB3.png
  # - assets/images/BOV_ITUB4.png
  # - assets/images/BOV_IVBX.png
  # - assets/images/BOV_IVVB11.png
  # - assets/images/BOV_JBSS3.png
  # - assets/images/BOV_JHSF3.png
  # - assets/images/BOV_KEPL3.png
  # - assets/images/BOV_KLBN11.png
  # - assets/images/BOV_KLBN4.png
  # - assets/images/BOV_KNRI11.png
  # - assets/images/BOV_LAME3.png
  # - assets/images/BOV_LAME4.png
  # - assets/images/BOV_LEVE3.png
  # - assets/images/BOV_LIGT3.png
  # - assets/images/BOV_LINX3.png
  # - assets/images/BOV_LLIS3.png
  # - assets/images/BOV_LOGN3.png
  # - assets/images/BOV_LPSB3.png
  # - assets/images/BOV_LREN3.png
  # - assets/images/BOV_LUPA3.png
  # - assets/images/BOV_LWSA3.png
  # - assets/images/BOV_MATB11.png
  # - assets/images/BOV_MCDC34.png
  # - assets/images/BOV_MDIA3.png
  # - assets/images/BOV_MERVAL.png
  # - assets/images/BOV_MGEL4.png
  # - assets/images/BOV_MGLU3.png
  # - assets/images/BOV_MILS3.png
  # - assets/images/BOV_MLCX.png
  # - assets/images/BOV_MMXM3.png
  # - assets/images/BOV_MNDL3.png
  # - assets/images/BOV_MNPR3.png
  # - assets/images/BOV_MRFG3.png
  # - assets/images/BOV_MRVE3.png
  # - assets/images/BOV_MULT3.png
  # - assets/images/BOV_MYPK3.png
  # - assets/images/BOV_NASDAQ.png
  # - assets/images/BOV_NIKKEI.png
  # - assets/images/BOV_NTCO3.png
  # - assets/images/BOV_ODPV3.png
  # - assets/images/BOV_OIBR3.png
  # - assets/images/BOV_OIBR4.png
  # - assets/images/BOV_OSXB3.png
  # - assets/images/BOV_OZUY.png
  # - assets/images/BOV_PCAR3.png
  # - assets/images/BOV_PDGR3.png
  # - assets/images/BOV_PETR3.png
  # - assets/images/BOV_PETR4.png
  # - assets/images/BOV_PETROLE.png
  # - assets/images/BOV_PFRM3.png
  # - assets/images/BOV_PIBB11.png
  # - assets/images/BOV_PINE4.png
  # - assets/images/BOV_PLAS3.png
  # - assets/images/BOV_PMAM3.png
  # - assets/images/BOV_POMO4.png
  # - assets/images/BOV_POSI3.png
  # - assets/images/BOV_PRIO3.png
  # - assets/images/BOV_PRSV11.png
  # - assets/images/BOV_PSSA3.png
  # - assets/images/BOV_PTBL3.png
  # - assets/images/BOV_PTNT4.png
  # - assets/images/BOV_QUAL3.png
  # - assets/images/BOV_RADL3.png
  # - assets/images/BOV_RAIL3.png
  # - assets/images/BOV_RAPT4.png
  # - assets/images/BOV_RCSL4.png
  # - assets/images/BOV_RDNI3.png
  # - assets/images/BOV_RENT3.png
  # - assets/images/BOV_ROMI3.png
  # - assets/images/BOV_RSID3.png
  # - assets/images/BOV_SANB11.png
  # - assets/images/BOV_SANB3.png
  # - assets/images/BOV_SANB4.png
  # - assets/images/BOV_SAPR11.png
  # - assets/images/BOV_SAPR4.png
  # - assets/images/BOV_SBSP3.png
  # - assets/images/BOV_SCAR3.png
  # - assets/images/BOV_SHPH11.png
  # - assets/images/BOV_SJCFUT.png
  # - assets/images/BOV_SLCE3.png
  # - assets/images/BOV_SLED4.png
  # - assets/images/BOV_SMAL11.png
  # - assets/images/BOV_SMLL.png
  # - assets/images/BOV_SMLS3.png
  # - assets/images/BOV_SMTO3.png
  # - assets/images/BOV_SP500.png
  # - assets/images/BOV_SULA11.png
  # - assets/images/BOV_SUZB3.png
  # - assets/images/BOV_TAEE11.png
  # - assets/images/BOV_TASA4.png
  # - assets/images/BOV_TCSA3.png
  # - assets/images/BOV_TEKA4.png
  # - assets/images/BOV_TELB3.png
  # - assets/images/BOV_TEND3.png
  # - assets/images/BOV_TIMP3.png
  # - assets/images/BOV_TOTS3.png
  # - assets/images/BOV_TPIS3.png
  # - assets/images/BOV_TRPL4.png
  # - assets/images/BOV_UGPA3.png
  # - assets/images/BOV_UNIP6.png
  # - assets/images/BOV_USCOM.png
  # - assets/images/BOV_USIM3.png
  # - assets/images/BOV_USIM5.png
  # - assets/images/BOV_USPAR.png
  # - assets/images/BOV_USPTAX.png
  # - assets/images/BOV_USTUR.png
  # - assets/images/BOV_UTIL.png
  # - assets/images/BOV_VALE3.png
  # - assets/images/BOV_VIVT3.png
  # - assets/images/BOV_VIVT4.png
  # - assets/images/BOV_VLID3.png
  # - assets/images/BOV_VVAR3.png
  # - assets/images/BOV_WEGE3.png
  # - assets/images/BOV_WHRL4.png
  # - assets/images/BOV_YDUQ3.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
